"use client";
import { useEffect, useState } from "react";
import { Anchor, ArrowDown, ArrowRight, Check, ExternalLink, Focus, Info, Layers3, LoaderCircle, Minus, Pause, Play, Plus, RotateCcw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import ImageComparison, {Panel} from "./image-comparison";
import ResultCharts from "./result-charts";
import {ko, modelName, pct} from "@/lib/display";
import Ocean from "./ocean";
import type {SceneMode,CadSelection} from "@/lib/ship-cad";
import type {ShipCommand} from "@/lib/ship-controls";
import DefenseExplorer from "./defense-explorer";
import VerificationStatus from "./verification-status";
import { validateEvidence, type Evidence, type Sample } from "@/lib/evidence";
export default function Home(){
 const [data,setData]=useState<Evidence|null>(null),[error,setError]=useState(""),[attempt,setAttempt]=useState(0);
 const [sampleId,setSampleId]=useState(""),[playing,setPlaying]=useState(false),[cameraCommand,setCameraCommand]=useState<{id:number;kind:ShipCommand}>({id:0,kind:"reset"}),[modelZoom,setModelZoom]=useState(1);
 const [sceneMode,setSceneMode]=useState<SceneMode>("sea"),[cadSelection,setCadSelection]=useState<CadSelection>("all");
 const structureNotes={all:"선체·갑판·상부 구조를 한눈에 살펴보세요.",hull:"선체는 배의 바깥 몸체입니다. 아래쪽 윤곽과 선수의 형태를 살펴보세요.",deck:"갑판은 배의 위쪽 작업 공간입니다. 난간과 작은 부속 구조를 살펴보세요.",upper:"갑판 위의 선교와 마스트를 살펴보세요. 단순화한 외형입니다."};
 const [activeSection,setActiveSection]=useState("");
 const [resultModel,setResultModel]=useState("cnn"),[epsilon,setEpsilon]=useState(0.03),[className,setClassName]=useState("all");
 useEffect(()=>{let active=true;fetch("/evidence/data.json").then(r=>{if(!r.ok)throw Error();return r.json();}).then(d=>{validateEvidence(d);if(active){setData(d);setSampleId(d.samples[0].id);}}).catch(()=>{if(active)setError("연구 기록을 확인하지 못했습니다. 확인되지 않은 수치는 표시하지 않습니다.");});return()=>{active=false};},[attempt]);
 useEffect(()=>{
  if(!data)return;
  let frame=0;
  const update=()=>{frame=0;let current="";for(const id of ["experiment","results","defense"]){const el=document.getElementById(id);if(el&&el.getBoundingClientRect().top<=140)current=id;}setActiveSection(current);};
  const schedule=()=>{if(!frame)frame=requestAnimationFrame(update)};
  window.addEventListener("scroll",schedule,{passive:true});window.addEventListener("resize",schedule);update();
  return()=>{window.removeEventListener("scroll",schedule);window.removeEventListener("resize",schedule);cancelAnimationFrame(frame)};
 },[data]);
 const sample=data?.samples.find(s=>s.id===sampleId),summary=data?.results.find(r=>r.model===resultModel&&r.epsilon===epsilon);
 const result=className==="all"?summary:summary?.classes.find(c=>c.name===className);
 const go=(id:string)=>document.getElementById(id)?.scrollIntoView({behavior:window.matchMedia("(prefers-reduced-motion: reduce)").matches?"instant":"smooth"});
 const choose=(s:Sample)=>setSampleId(s.id);
 const cameraAction=(kind:ShipCommand)=>{setPlaying(false);setCameraCommand(c=>({id:c.id+1,kind}));};
 return <main><header className="topbar"><a href="#" className="brand"><Anchor size={25}/><span>MARIS <small>해양 AI 실험실</small></span></a><nav><a href="#experiment">이미지 실험</a><a href="#results">전체 결과</a><a href="#defense">방어 실험</a><a href="#progress">진행 상태</a></nav><span className="replay-badge"><span/>기록된 결과 재생</span></header>
 <section className="scene-section" aria-label="설명용 3D 해상 장면">
  <div className="scene-intro"><span className="eyebrow">MARITIME ADVERSARIAL AI</span><p className="scene-kicker">눈에는 비슷한 사진. AI의 답도 같을까요?</p><h1>같은 선박,<br/>왜 AI의 판단은<br/>달라질까?</h1><p>사진의 작은 픽셀 변화가 AI의 답을 바꿀 수 있습니다.<br/>실제 공격 기록과 두 필터의 한계를 직접 비교하세요.</p><Button className="primary-action" onClick={()=>go("experiment")}>실제 이미지 비교하기 <ArrowDown size={17}/></Button><span className="scene-replay">저장된 실험 기록 재생 · 실시간 추론 아님</span>{sample&&<div className="hero-finding"><span>아래에서 확인할 실제 사례</span><strong>{ko(sample.cleanPrediction)} <ArrowRight size={20}/> {ko(sample.attackPrediction)}</strong><small>{modelName(sample.model)} · ε {sample.epsilon} · {sample.success?"공격 후 오답 전환":"공격 후 정답 유지"}</small></div>}</div>
  <div className="scene-workspace"><div className="stage-heading"><span>01 / 선박 관찰</span><span>설명용 3D 공간</span></div><div className="scene-mode" role="group" aria-label="설명용 모형 표시 방식">{([["sea","해상 모형"],["cad","CAD 구조 보기"]] as const).map(([value,label])=><button key={value} aria-pressed={sceneMode===value} onClick={()=>{setPlaying(false);setSceneMode(value)}}>{value==="cad"?<Layers3 size={17}/>:<Anchor size={17}/>} {label}</button>)}<span>같은 모형, 다른 관찰 방식</span></div><div className={"scene-stage"+(sceneMode==="cad"?" cad-stage":"")}><Ocean playing={playing} command={cameraCommand} mode={sceneMode} selection={cadSelection} onInteract={()=>setPlaying(false)} onZoom={setModelZoom}/><span className="scene-label">{sceneMode==="cad"?"MARIS / STRUCTURE STUDY":"MARIS / MODEL STUDY"}</span>{sceneMode==="cad"&&<span className="cad-stamp">치수 없는 설명용 모형<br/>실제 설계도 아님</span>}<span className="orbit-hint">드래그로 회전 · 휠 / 두 손가락으로 확대</span></div>{sceneMode==="cad"&&<div className="cad-inspector"><div role="group" aria-label="살펴볼 선박 구조">{([["all","전체"],["hull","선체"],["deck","갑판"],["upper","상부 구조"]] as const).map(([value,label])=><button key={value} aria-pressed={cadSelection===value} onClick={()=>{setPlaying(false);setCadSelection(value)}}>{label}</button>)}</div><p aria-live="polite">{structureNotes[cadSelection]}</p><small>밝은 윤곽은 선택한 구조입니다. AI 분석·공격 효과를 표시하지 않습니다.</small></div>}<div className="view-presets" role="group" aria-label="선박 관찰 시점"><span>관찰 시점</span><Button variant="outline" onClick={()=>cameraAction("bow")}>선수 · 앞쪽</Button><Button variant="outline" onClick={()=>cameraAction("side")}>선체 · 옆쪽</Button><Button variant="outline" onClick={()=>cameraAction("deck")}>갑판 · 위쪽</Button></div><div className="orbit-controls"><div><Button variant="outline" aria-label="선박 축소" size="icon" onClick={()=>cameraAction("out")}><Minus/></Button><output aria-label="선박 확대 배율">{modelZoom.toFixed(1)}×</output><Button variant="outline" aria-label="선박 확대" size="icon" onClick={()=>cameraAction("in")}><Plus/></Button></div><Button variant="outline" onClick={()=>cameraAction("reset")}><RotateCcw size={15}/>시점 초기화</Button><Button variant="outline" aria-pressed={playing} onClick={()=>setPlaying(p=>!p)}>{playing?<Pause size={15}/>:<Play size={15}/>}자동 회전 {playing?"끄기":"켜기"}</Button></div><p className="model-boundary">설명용 선박이며 실제 실험 이미지의 선박을 재현하지 않습니다. 항해 제어 실험이 아닙니다.</p></div>
 </section>
 <div className="experiment-body"><nav className="flow-strip" aria-label="실험 목차">{([["experiment","이미지 비교"],["results","전체 결과"],["defense","방어 실험"]] as const).map(([id,label],i)=><a key={id} href={"#"+id} aria-current={activeSection===id?"location":undefined} className={activeSection===id?"active":""}><b>{String(i+1).padStart(2,"0")}</b>{label}</a>)}<span className="provisional">예비 연구 결과 · PROVISIONAL</span></nav>
 {error?<div role="alert" className="load-state"><Info/><h2>결과 연결을 확인해주세요</h2><p>{error}</p><Button onClick={()=>{setError("");setAttempt(a=>a+1)}}>다시 불러오기</Button></div>:!data||!sample?<div className="load-state" role="status"><LoaderCircle className="spin"/>확인된 실험 기록을 불러오는 중입니다.</div>:<>
 <section id="experiment" className="lab-section"><div className="section-heading"><div><span className="eyebrow">01 / IMAGE EXPERIMENT</span><h2>작은 변화가 만든 판단의 차이.</h2></div><p>저장된 비교 그림 {data.samples.length}개 · FGSM ε = {sample.epsilon}<br/><span>FGSM: 한 번의 픽셀 교란으로 오분류를 유도하는 방법</span></p></div>
 <div className="experiment-grid"><aside className="sample-picker"><div className="picker-title"><Layers3 size={17}/><h3>실험 이미지 선택</h3><span>{data.samples.length}</span></div><p>모델과 성공·실패를 함께 살펴보세요. 모든 사례의 강도는 ε = 0.03입니다.</p><div className="sample-list">{data.samples.map((s,i)=><button key={s.id} onClick={()=>choose(s)} className={`sample-card ${sample.id===s.id?"selected":""}`} aria-pressed={sample.id===s.id}><Panel sample={s} part={0} compact/><div><small>CASE {String(i+1).padStart(2,"0")} · {modelName(s.model)}</small><strong>{ko(s.truth)}</strong><span>{s.success?"공격 성공 · 오답 전환":"공격 실패 · 정답 유지"}</span></div>{sample.id===s.id&&<Check size={15}/>}</button>)}</div><div className="dataset-note"><Info size={16}/><p>현재 공개된 비교 PNG는 항공모함 {data.samples.length}개뿐입니다. 전체 {data.total}장이나 다른 선종의 대표 사례로 일반화할 수 없습니다.</p></div></aside>
 <ImageComparison key={sample.id} sample={sample}/></div>
 <div className="meaning-note"><Focus size={22}/><p><strong>이 실험이 보여주는 것</strong>입력 픽셀의 변화가 선박 분류에 미치는 영향입니다. 위 이미지 비교는 방어 없는 공격 기록입니다. 방어 실험은 아래에 따로 제시하며 충돌·항로 이탈·센서 공격은 측정하지 않았습니다.</p><a href="#results">전체 기록 살펴보기 <ArrowDown size={16}/></a></div></section>
 <section id="results" className="results-section"><div className="section-heading"><div><span className="eyebrow">02 / EXPERIMENT EVIDENCE</span><h2>한 장을 넘어, 전체 실험으로.</h2></div><p>{data.total}장의 동일 테스트셋으로 비교한 기록<br/><span>실시간 추론 없이 저장된 수치를 재생합니다.</span></p></div><div className="result-current" aria-live="polite"><span>현재 통계</span><strong>{modelName(resultModel)} · ε {epsilon} · {className==="all"?"전체 선박":ko(className)}</strong><small>저장된 실험 기록 · 예비 결과</small></div>{result&&<><div className="metric-grid"><div className="metric"><span>정상 정확도</span><strong>{pct(result.cleanCorrect/result.n)}</strong><small>전체 {result.n}장 중 {result.cleanCorrect}장 정답</small></div><div className="metric"><span>공격 후 정확도</span><strong>{pct(result.robustCorrect/result.n)}</strong><small>전체 {result.n}장 중 {result.robustCorrect}장 정답</small></div><div className="metric accent"><span>공격 성공률 <i>ASR</i></span><strong>{pct(result.asr)}</strong><small>정상 정답 {result.cleanCorrect}장 중 {result.successes}장 오답 전환</small></div></div></>}
 <p className="asr-help">공격 성공률(ASR)은 <strong>원래 맞혔던 이미지 중 공격 후 틀린 비율</strong>입니다.</p>
 <div className="case-context"><p><strong>{resultModel!==sample.model||epsilon!==sample.epsilon||className!==sample.truth?"위 이미지 사례와 집계 조건이 다릅니다.":"위 이미지와 같은 모델·강도·선종의 집계입니다."}</strong> 위 사례: {modelName(sample.model)} · ε {sample.epsilon} · {ko(sample.truth)}. 통계는 여러 이미지의 집계이며, 선택해도 위 이미지는 바뀌지 않습니다.</p><Button variant="outline" onClick={()=>{setResultModel(sample.model);setEpsilon(sample.epsilon);setClassName(sample.truth);}}>사례 조건에 맞추기</Button></div>
 <Accordion type="single" collapsible className="result-filter-panel"><AccordionItem value="filters"><AccordionTrigger>다른 조건 살펴보기 <span>모델 · 선종 · 공격 강도</span></AccordionTrigger><AccordionContent><div className="result-controls"><div><label htmlFor="result-model">모델</label><select id="result-model" value={resultModel} onChange={e=>setResultModel(e.target.value)}>{data.models.map(m=><option key={m} value={m}>{modelName(m)}</option>)}</select></div><div><label htmlFor="result-class">선박 클래스</label><select id="result-class" value={className} onChange={e=>setClassName(e.target.value)}><option value="all">전체 선박</option>{data.classNames.map(c=><option key={c} value={c}>{ko(c)}</option>)}</select></div><fieldset><legend>공격 강도 ε <span>픽셀 변화의 허용 크기</span></legend><div className="epsilon-options">{data.epsilons.map(e=><Button key={e} variant="outline" aria-pressed={epsilon===e} className={epsilon===e?"selected":""} onClick={()=>setEpsilon(e)}>{e===0?"0 · 대조군":e}</Button>)}</div></fieldset></div></AccordionContent></AccordionItem></Accordion>
 {result&&<><div className="chart-panel"><h3>공격 전부터 틀린 이미지와 구분합니다.</h3><p>ASR 분모에는 정상 입력에서 맞힌 이미지만 포함됩니다.</p><div className="composition" aria-label={`기존 오답 ${result.n-result.cleanCorrect}장, 공격으로 오답 ${result.successes}장, 정답 유지 ${result.cleanCorrect-result.successes}장`}><span className="preexisting" style={{width:`${(result.n-result.cleanCorrect)/result.n*100}%`}}/><span className="flipped" style={{width:`${result.successes/result.n*100}%`}}/><span className="retained" style={{width:`${(result.cleanCorrect-result.successes)/result.n*100}%`}}/></div><div className="chart-legend"><span><i className="preexisting"/>기존 오답 <b>{result.n-result.cleanCorrect}</b></span><span><i className="flipped"/>공격으로 오답 전환 <b>{result.successes}</b></span><span><i className="retained"/>정답 유지 <b>{result.cleanCorrect-result.successes}</b></span></div><small>기존 오답이 공격 후 정답으로 바뀌는 경우는 공격 후 정확도에는 포함되지만 ASR에는 포함되지 않습니다.</small></div></>}
 <ResultCharts data={data} className={className}/>
 <details className="record-table"><summary>전체 선박 · 두 모델 · 모든 강도 원수치 보기</summary><div className="table-scroll"><table><thead><tr><th>모델</th><th>ε</th><th>정상 정확도</th><th>공격 후 정확도</th><th>ASR</th><th>성공 / 분모</th></tr></thead><tbody>{data.results.map(r=><tr key={`${r.model}-${r.epsilon}`}><th>{modelName(r.model)}</th><td>{r.epsilon}</td><td>{pct(r.cleanCorrect/r.n)}</td><td>{pct(r.robustCorrect/r.n)}</td><td>{pct(r.asr)}</td><td>{r.successes} / {r.cleanCorrect}</td></tr>)}</tbody></table></div></details><div className="boundaries"><Info size={19}/><p>ε는 기록된 값만 선택할 수 있으며 보간하지 않습니다. 입력 해상도는 CNN 128×128, MobileNetV2 224×224로 다릅니다. MobileNetV2 학습 당시 전처리는 직접 확인되지 않았습니다. 결과는 예비 상태입니다.</p></div></section>
 <section id="progress" className="results-section"><div className="section-heading"><div><span className="eyebrow">RESEARCH PROGRESS</span><h2>우리 연구, 어디까지 왔나?</h2></div></div><div className="metric-grid"><div className="metric"><span>실험 범위 확정</span><h3>선박 이미지 분류</h3><p>CNN · MobileNetV2, FGSM ε = {data.epsilons.join(" / ")}. 입력 [0,1]에서 픽셀 변화의 허용 크기입니다.</p></div><div className="metric"><span>구현·실험 완료</span><h3>공격 + 전처리 방어</h3><p>고정 3×3 가우시안·평균 필터와 방어를 고려한 FGSM까지 실행했습니다. 모델을 재학습하지 않았습니다.</p></div><div className="metric"><span>보존된 연구 기록</span><h3>확정 범위 실험 완료</h3><p>원자료의 provisional·experimental 표기는 보존 이력입니다. 아래에서 재실행 검증 상태를 따로 확인할 수 있습니다.</p></div></div><VerificationStatus/></section>
 <DefenseExplorer/>
 <section className="missing-evidence" aria-label="연구 범위와 데이터 상세"><Accordion type="single" collapsible><AccordionItem value="research-data"><AccordionTrigger>연구 범위·데이터 안내</AccordionTrigger><AccordionContent><h4>다른 선종의 비교는 언제 추가되나요?</h4><p>검증된 실제 비교 자료가 확보되면 추가합니다. 현재 항공모함 사례만으로 다른 선종이나 전체 실험을 대표한다고 볼 수 없습니다.</p><h4>더 정밀한 차이 분석에 필요한 자료</h4><p>같은 표본의 정상·공격 입력 배열(NPY/NPZ), 모델·ε·표본 경로와 연결된 메타데이터, 공격 성공·실패를 함께 담은 다른 선종의 비교 PNG가 필요합니다. 새 자료는 연구 감사를 거친 뒤 연결합니다.</p></AccordionContent></AccordionItem>
<AccordionItem value="evidence-reading"><AccordionTrigger>이 실험은 어떻게 확인하나요?</AccordionTrigger><AccordionContent><h4>조건부터 확인합니다</h4><p>어떤 모델에 어떤 이미지를 넣고, 얼마만큼 바꿨는지 먼저 확인합니다. 같은 조건의 정상·공격 결과를 비교하고, 방어 실험에서는 정상 이미지의 성능 저하도 함께 봅니다.</p><h4>숫자는 기록으로 되짚습니다</h4><p>정확도는 전체 표본 중 맞힌 비율입니다. 공격 성공률은 정상 입력에서 맞힌 표본 중 공격 후 틀린 비율입니다. 화면의 근거 저장소와 파일 해시·출처에서 기록을 확인할 수 있습니다.</p><h4>확인한 것과 남은 것을 나눕니다</h4><p>코드 검사 통과, 저장된 결과 검산, 실제 환경에서의 성능 검증은 서로 다릅니다. 검토 의견은 대상 기록·판단 이유·미확인 사항을 함께 남기며, AI가 작성한 설명도 사람의 확인을 거칩니다.</p></AccordionContent></AccordionItem>
<AccordionItem value="engineering-context"><AccordionTrigger>해양·방산 연구와는 어떻게 연결되나요?</AccordionTrigger><AccordionContent><h4>연결점은 ‘조건을 정하고 근거로 검증하는 일’입니다</h4><p>방산 직무 자료의 요구사항 추적과 시험평가 관점은 이 연구를 설명하는 데 참고할 수 있습니다. 우리는 평가조건, 표본 기록, 검사 결과를 연결해 선박 이미지 분류기의 취약성과 전처리 방어의 한계를 확인합니다.</p><h4>현재 확인한 범위</h4><p>저장된 선박 이미지에 대한 분류 실험입니다. 함정 운용·표적 추적·항법 제어·전자전·군용 환경시험의 성능을 검증한 것은 아닙니다. 화면의 3D 선박은 설명용이며 운용 시험장이 아닙니다.</p><h4>다음 단계에는 별도의 근거가 필요합니다</h4><p>실해역 영상, 센서 결합, 하드웨어 연동은 별도 데이터와 시험계획이 필요한 후속 과제입니다. FGSM 공격 성공률을 실제 선박 공격 가능성이나 사고 확률로 해석할 수 없습니다.</p><p>직무 강의는 연구 절차를 이해하기 위한 배경 참고이며, 실험 결과의 증거나 군용 규격 인증 근거가 아닙니다.</p></AccordionContent></AccordionItem></Accordion></section>
 <section className="evidence-footer"><div><span className="eyebrow">TRACEABLE BY DESIGN</span><h3>모든 숫자에는 근거가 있습니다.</h3><p>표본 기록에서 계산 · 설명용 3D와 실험 결과 분리</p></div><div><a href={data.repoUrl+"/tree/"+data.sourceCommit} target="_blank" rel="noreferrer">근거 저장소 <ExternalLink size={15}/></a><a href="/evidence/provenance.json" target="_blank">파일 해시·출처</a><span>기준 커밋 {data.sourceCommit.slice(0,7)}</span></div></section></>}
 </div><footer><span><Anchor size={16}/> MARIS · AdversarialAI_Security</span><span>선박 이미지 분류 강건성 연구</span></footer></main>;
}
